### ISSUE TITLE
getpwuid(): uid not found: 912296

### ISSUE THREAD

**Issue by gowthamakanthan** [mullnerz/docker-ansible-playbook#4]
Team, 

 Am trying to use this container in a CICD(Jenkins) to provision various tasks. Unfortunately getting below error. Could you please check?

> `
+ ansible --version
Traceback (most recent call last):
  File "/usr/bin/ansible", line 63, in <module>
    from ansible.utils.display import Display
  File "/usr/lib/python3.8/site-packages/ansible/utils/display.py", line 60, in <module>
    class FilterUserInjector(logging.Filter):
  File "/usr/lib/python3.8/site-packages/ansible/utils/display.py", line 65, in FilterUserInjector
    username = getpass.getuser()
  File "/usr/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 912296'
`

**Comment by mullnerz** [comment]
Cannot reproduce the issue.

Tested on Ubuntu 20.04 and it just works:

```
➜  ~ docker run mullnerz/ansible-playbook ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
```
